/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bloodbank;

import java.util.HashMap;
import java.util.concurrent.TimeUnit;
/**
 *
 * @author johncalkins
 */
public class BloodBank extends javax.swing.JFrame {
    
    
    //START OF MY VARIABLES
    
    private static String currentUser;
    private static boolean ownerClearence;
    
    //User-password hashMap
    private static HashMap<String, String> usersHashMap = new HashMap<>();
    
    static{
        usersHashMap.put("Owner", "C2TKNFYt");
    }
    
    //END OF MY VARIABLES
    
    
    
    
    
    /**
     * Creates new form BloodBank
     */
    public BloodBank() {
        initComponents();
        loginNewUserButton.setVisible(false);
        loginNotificationLabel.setVisible(false);
    }
    
    
    
    //START OF MY FUNCTIONS
    
    //Updates the current notification
    private void loginNotificationUpdate(String message){
        //Change and enable loginNotificationLabel
        loginNotificationLabel.setText(message);
        loginNotificationLabel.setVisible(true);
    }
    
    //END OF MY FUNCTIONS

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginFailurePopupMenu = new javax.swing.JPopupMenu();
        tabbedPane = new javax.swing.JTabbedPane();
        homePane = new javax.swing.JPanel();
        databasePane = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        loginUserLabel = new javax.swing.JLabel();
        loginPasswordLabel = new javax.swing.JLabel();
        loginUserTextField = new javax.swing.JTextField();
        loginPasswordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        loginNewUserButton = new javax.swing.JButton();
        loginCurrentUserLabel = new javax.swing.JLabel();
        loginNotificationLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        homePane.setBackground(new java.awt.Color(249, 226, 226));

        javax.swing.GroupLayout homePaneLayout = new javax.swing.GroupLayout(homePane);
        homePane.setLayout(homePaneLayout);
        homePaneLayout.setHorizontalGroup(
            homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        homePaneLayout.setVerticalGroup(
            homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Home", homePane);

        databasePane.setBackground(new java.awt.Color(248, 196, 196));

        javax.swing.GroupLayout databasePaneLayout = new javax.swing.GroupLayout(databasePane);
        databasePane.setLayout(databasePaneLayout);
        databasePaneLayout.setHorizontalGroup(
            databasePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        databasePaneLayout.setVerticalGroup(
            databasePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Database", databasePane);

        loginPanel.setBackground(new java.awt.Color(255, 153, 153));

        loginUserLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        loginUserLabel.setText("Username:");

        loginPasswordLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        loginPasswordLabel.setText("Password:");

        loginButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        loginNewUserButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        loginNewUserButton.setText("New User");
        loginNewUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginNewUserButtonActionPerformed(evt);
            }
        });

        loginCurrentUserLabel.setBackground(new java.awt.Color(255, 204, 204));
        loginCurrentUserLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        loginCurrentUserLabel.setText("No User");
        loginCurrentUserLabel.setOpaque(true);

        loginNotificationLabel.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        loginNotificationLabel.setText("Notification Label");

        logoutButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(loginPasswordLabel)
                                    .addComponent(loginUserLabel))
                                .addGap(27, 27, 27)
                                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(loginUserTextField)
                                    .addComponent(loginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(logoutButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(loginButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(loginNewUserButton, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(loginNotificationLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginCurrentUserLabel)))
                .addContainerGap())
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginCurrentUserLabel)
                .addGap(5, 5, 5)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginUserLabel)
                    .addComponent(loginUserTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginNotificationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginPasswordLabel)
                    .addComponent(loginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton)
                    .addComponent(logoutButton))
                .addGap(18, 18, 18)
                .addComponent(loginNewUserButton)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Login", loginPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>                        

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        //Take input from loginUserTextField and loginPasswordField converting the laters' char[] to String
        String userInput = loginUserTextField.getText();
        String passwordInput = new String(loginPasswordField.getPassword());
        
        //First check that the user exists and if it does that the password matches
        if(usersHashMap.get(userInput) == null || (!usersHashMap.get(userInput).equals(passwordInput))){
            //Message
            loginNotificationUpdate("Username or password is incorrect.");
            
            //Reset fields
            loginUserTextField.setText("");
            loginPasswordField.setText("");
        } else{
            //Set user & clear input fields
            currentUser = userInput;
            loginCurrentUserLabel.setText(currentUser);
            
            
            //Set clearence level
            ownerClearence = (currentUser.equals("Owner")) ? true: false;
            
            if(ownerClearence){
                loginNewUserButton.setVisible(true);
            } else{
                loginNewUserButton.setVisible(false);
            }
            
            //Message
            loginNotificationUpdate("Successfully logged in!");
            
            //Reset fields
            loginUserTextField.setText("");
            loginPasswordField.setText("");
        }
        
        
        
    }                                           

    private void loginNewUserButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        //Get input from fields, format password input from char[] to String
        String newUser = loginUserTextField.getText();
        String newPassword = new String(loginPasswordField.getPassword());
        
        //Check that the user doesn't already exist
        if(usersHashMap.get(newUser) != null){
            //Message
            loginNotificationUpdate("User already exists.");
            
            //Reset fields
            loginUserTextField.setText("");
            loginPasswordField.setText("");
        } else{
            //Create user (this will need to be saved to the server)
            usersHashMap.put(newUser, newPassword);
            
            //Message
            loginNotificationUpdate("Successfully created new user.");
            
            //Reset fields
            loginUserTextField.setText("");
            loginPasswordField.setText("");
        }
    }                                                  

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        currentUser = null;
        ownerClearence = false;
        loginNewUserButton.setVisible(false);
        loginCurrentUserLabel.setText("No User");
        
        loginNotificationUpdate("Successfully logged out.");
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BloodBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BloodBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BloodBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BloodBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BloodBank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel databasePane;
    private javax.swing.JPanel homePane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginCurrentUserLabel;
    private javax.swing.JPopupMenu loginFailurePopupMenu;
    private javax.swing.JButton loginNewUserButton;
    private javax.swing.JLabel loginNotificationLabel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField loginPasswordField;
    private javax.swing.JLabel loginPasswordLabel;
    private javax.swing.JLabel loginUserLabel;
    private javax.swing.JTextField loginUserTextField;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration                   
}
