/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package BloodBankManagement;

import BloodBankManagement.LoginPage;
import BloodBankManagement.ActivityLog;

/**
 *
 * @author pault
 */
public class DeleteUser extends javax.swing.JInternalFrame {

    /**
     * Creates new form DeleteUser
     */
    public DeleteUser() {
        initComponents();
        errorOptionPane.setVisible(false);
    }
    
      //PAUL'S FUNCTIONS
    
    //Show errorOptionPane and set text
    private void showError(String errorMessage){
        errorOptionPane.setMessage(errorMessage);
        errorOptionPane.setVisible(true);
        
        try{
            errorOptionPane.createDialog("Error").setVisible(true);
        } catch(Exception e){
            //handle exception, HeadlessException
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteUserPanel = new javax.swing.JPanel();
        usernameTextField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        currentUserPasswordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        errorOptionPane = new javax.swing.JOptionPane();
        exitButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(180, 180));
        setPreferredSize(new java.awt.Dimension(450, 350));

        deleteUserPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delete User", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 0, 14))); // NOI18N

        usernameLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        usernameLabel.setText("Username:");

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel1.setText("Current User Password:");

        deleteButton.setBackground(new java.awt.Color(255, 0, 0));
        deleteButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        errorOptionPane.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N

        exitButton.setBackground(new java.awt.Color(255, 0, 0));
        exitButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deleteUserPanelLayout = new javax.swing.GroupLayout(deleteUserPanel);
        deleteUserPanel.setLayout(deleteUserPanelLayout);
        deleteUserPanelLayout.setHorizontalGroup(
            deleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteUserPanelLayout.createSequentialGroup()
                .addGroup(deleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deleteUserPanelLayout.createSequentialGroup()
                        .addGroup(deleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(deleteUserPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(deleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameLabel)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(deleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(currentUserPasswordField)
                                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(deleteUserPanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(errorOptionPane, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteButton)))
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteUserPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exitButton)))
                .addContainerGap())
        );
        deleteUserPanelLayout.setVerticalGroup(
            deleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel))
                .addGap(26, 26, 26)
                .addGroup(deleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentUserPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(deleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deleteUserPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(errorOptionPane, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(deleteUserPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deleteUserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deleteUserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        String deleteUsername = usernameTextField.getText();
        String currentPassword = new String(currentUserPasswordField.getPassword());
        
        //Ensure validity
        if(LoginPage.userHashMap.get(deleteUsername) == null){
            showError("This user does not exist.");
            return;
        } else if(LoginPage.userHashMap.get(deleteUsername).getActive()){
            //THIS DOESN'T WORK, IDK WHY
            //WON'T SEND AN ERROR WHEN THE USERNAME DOESN'T EXIST
            showError("Cannot delete current user.");
            return;
        } else if(!LoginPage.userHashMap.get(LoginPage.currentUsername).getPassword().equals(currentPassword)){
            showError("Password is incorrect.");
            return;
        } else if(!LoginPage.userHashMap.get(LoginPage.currentUsername).getRoleType().equals("Admin")){
            showError("You do not have admin permission.");
            return;
        } else if(deleteUsername.equals("Admin")){
            showError("Cannot delete the Admin user.");
            return;
        }
        
        //Delete user
        LoginPage.userHashMap.remove(deleteUsername);
        
        //Clear fields
        usernameTextField.setText("");
        currentUserPasswordField.setText("");
        
        //Write action to activity log
        ActivityLog.writeToActivityLogFile("Deleted user: " + deleteUsername);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField currentUserPasswordField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel deleteUserPanel;
    private javax.swing.JOptionPane errorOptionPane;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
