/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package BloodBankManagement;

import java.io.File;  // Import the File class
import java.io.FileNotFoundException;  // Import this class to handle errors
import java.util.Scanner; // Import the Scanner class to read text files

//TEMP
import java.io.FileWriter;   // Import the FileWriter class
import java.io.IOException;  // Import the IOException class to handle errors

/**
 *
 * @author pault
 */
public class ActivityLog extends javax.swing.JInternalFrame {

    /**
     * Creates new form ActionLog
     */
    public ActivityLog() {
        initComponents();
    }
    
    
    // MY FUNCTION
    //Read the text from the activityLog file
    //Save that line-to-line
    //Then change the text of the activityLogTextAre
    private boolean updateActivityLog(){
        
        try {
            File activityLogFile = new File("activityLog.txt");
            String logUpdate;
            String currentLogText = "";
            
            Scanner myReader = new Scanner(activityLogFile);

            while(myReader.hasNextLine()){
                logUpdate = myReader.nextLine();
                currentLogText += (logUpdate + "\n");
            }
            
            myReader.close();
            activityLogTextArea.setText(currentLogText);
            
        } catch(FileNotFoundException e){
            //Display error
            return false;
        }
        
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        activityLogPanel = new javax.swing.JPanel();
        activityLogTextArea = new javax.swing.JTextArea();
        exitButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();

        activityLogPanel.setBackground(new java.awt.Color(239, 245, 250));
        activityLogPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Activity Log", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 0, 16), new java.awt.Color(204, 0, 0))); // NOI18N

        activityLogTextArea.setEditable(false);
        activityLogTextArea.setBackground(new java.awt.Color(255, 255, 255));
        activityLogTextArea.setColumns(20);
        activityLogTextArea.setLineWrap(true);
        activityLogTextArea.setRows(5);
        activityLogTextArea.setCaretColor(new java.awt.Color(255, 255, 255));
        activityLogTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        activityLogTextArea.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                activityLogTextAreaPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout activityLogPanelLayout = new javax.swing.GroupLayout(activityLogPanel);
        activityLogPanel.setLayout(activityLogPanelLayout);
        activityLogPanelLayout.setHorizontalGroup(
            activityLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activityLogPanelLayout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(activityLogTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );
        activityLogPanelLayout.setVerticalGroup(
            activityLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activityLogPanelLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(activityLogTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        exitButton.setBackground(new java.awt.Color(255, 0, 0));
        exitButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(activityLogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(updateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(activityLogPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton)
                    .addComponent(updateButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        
        /*  TESTING READING/WRITING,  REMOVE WHEN ACTUAL LOGS ARE IMPLEMENTED
        try{
            FileWriter myWriter = new FileWriter("activityLog.txt");
            myWriter.write("Java files are hard!");
            myWriter.write("\nNext line please");
            myWriter.write("\nOK");
            myWriter.close();
        } catch(IOException e){
            //Display error
        }
        */
        
        updateActivityLog();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void activityLogTextAreaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_activityLogTextAreaPropertyChange
        // TODO add your handling code here:z
        updateActivityLog();
    }//GEN-LAST:event_activityLogTextAreaPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel activityLogPanel;
    private javax.swing.JTextArea activityLogTextArea;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
