/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package BloodBankManagement;

/**
 *
 * @author Souleymane.Sono
 */
public class DonorMenu extends javax.swing.JInternalFrame {

    /**
     * Creates new form DonorMenu
     */
    public DonorMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JButton();
        addNewDonorButton = new javax.swing.JButton();
        updateDonorInfoButton = new javax.swing.JButton();
        removeDonor = new javax.swing.JButton();
        showDonorListButton = new javax.swing.JButton();
        moreLabel = new javax.swing.JLabel();
        donateBloodImageLabel = new javax.swing.JLabel();
        donorMenuLabel = new javax.swing.JLabel();
        seeReportButton = new javax.swing.JButton();
        DonorPane = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Donor Menu");
        setFocusable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitButton.setBackground(new java.awt.Color(204, 0, 0));
        exitButton.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 780, 100, 30));

        addNewDonorButton.setBackground(new java.awt.Color(204, 0, 0));
        addNewDonorButton.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        addNewDonorButton.setForeground(new java.awt.Color(255, 255, 255));
        addNewDonorButton.setText("Add New Donor");
        addNewDonorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewDonorButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addNewDonorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 180, 30));

        updateDonorInfoButton.setBackground(new java.awt.Color(204, 0, 0));
        updateDonorInfoButton.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        updateDonorInfoButton.setForeground(new java.awt.Color(255, 255, 255));
        updateDonorInfoButton.setText("update Donor Info");
        getContentPane().add(updateDonorInfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 30));

        removeDonor.setBackground(new java.awt.Color(204, 0, 0));
        removeDonor.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        removeDonor.setForeground(new java.awt.Color(255, 255, 255));
        removeDonor.setText("Remove Donor");
        getContentPane().add(removeDonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 180, 30));

        showDonorListButton.setBackground(new java.awt.Color(204, 0, 0));
        showDonorListButton.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        showDonorListButton.setForeground(new java.awt.Color(255, 255, 255));
        showDonorListButton.setText("Show Donor list");
        getContentPane().add(showDonorListButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 170, 30));

        moreLabel.setBackground(new java.awt.Color(204, 0, 0));
        moreLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "More", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 0, 24), new java.awt.Color(204, 0, 0))); // NOI18N
        getContentPane().add(moreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 430, 220));

        donateBloodImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngegg (28).png"))); // NOI18N
        getContentPane().add(donateBloodImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 170, 170));

        donorMenuLabel.setBackground(new java.awt.Color(204, 0, 0));
        donorMenuLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Donor Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 0, 24), new java.awt.Color(204, 0, 0))); // NOI18N
        getContentPane().add(donorMenuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 437, 840));

        seeReportButton.setBackground(new java.awt.Color(204, 0, 0));
        seeReportButton.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        seeReportButton.setForeground(new java.awt.Color(255, 255, 255));
        seeReportButton.setText("see Report");
        getContentPane().add(seeReportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 180, 30));

        DonorPane.setAutoscrolls(true);
        DonorPane.setFocusable(false);
        getContentPane().add(DonorPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 910, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addNewDonorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewDonorButtonActionPerformed
        // TODO add your handling code here:
        Registration reg = new Registration();
        DonorPane.add(reg).setVisible(true);
        
        
        
        
    }//GEN-LAST:event_addNewDonorButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DonorPane;
    private javax.swing.JButton addNewDonorButton;
    private javax.swing.JLabel donateBloodImageLabel;
    private javax.swing.JLabel donorMenuLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel moreLabel;
    private javax.swing.JButton removeDonor;
    private javax.swing.JButton seeReportButton;
    private javax.swing.JButton showDonorListButton;
    private javax.swing.JButton updateDonorInfoButton;
    // End of variables declaration//GEN-END:variables
}
