/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package BloodBankManagement;

/**
 *
 * @author Souleymane.Sono
 */
public class Inventory extends javax.swing.JInternalFrame {

    /**
     * Creates new form Inventory
     */
    public Inventory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bPositiveButton = new javax.swing.JButton();
        abPositiveButton = new javax.swing.JButton();
        aNegativeButton = new javax.swing.JButton();
        oPositiveButton = new javax.swing.JButton();
        aPositiveButton = new javax.swing.JButton();
        oNegativeButton = new javax.swing.JButton();
        bNegativeButton = new javax.swing.JButton();
        abNegativeButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        inventoryLabel = new javax.swing.JLabel();
        bloodTypeLabel = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Inventory");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bPositiveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/B+.png"))); // NOI18N
        bPositiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPositiveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(bPositiveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 140, 130));

        abPositiveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AB+.png"))); // NOI18N
        abPositiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abPositiveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(abPositiveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 140, 130));

        aNegativeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A-.png"))); // NOI18N
        aNegativeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aNegativeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(aNegativeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 140, 130));

        oPositiveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O+.png"))); // NOI18N
        oPositiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oPositiveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(oPositiveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 140, 130));

        aPositiveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A+.png"))); // NOI18N
        aPositiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aPositiveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(aPositiveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 140, 130));

        oNegativeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/O+.png"))); // NOI18N
        oNegativeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oNegativeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(oNegativeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 140, 130));

        bNegativeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/B-.png"))); // NOI18N
        bNegativeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNegativeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(bNegativeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 140, 130));

        abNegativeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AB-.png"))); // NOI18N
        abNegativeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abNegativeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(abNegativeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 140, 130));

        exitButton.setBackground(new java.awt.Color(204, 0, 0));
        exitButton.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 90, 30));

        inventoryLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inventory", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 0, 24), new java.awt.Color(204, 0, 0))); // NOI18N
        getContentPane().add(inventoryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 710, 470));

        bloodTypeLabel.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        bloodTypeLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Blood Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 0, 18), new java.awt.Color(204, 0, 0))); // NOI18N
        getContentPane().add(bloodTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 680, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bPositiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPositiveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bPositiveButtonActionPerformed

    private void abPositiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abPositiveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abPositiveButtonActionPerformed

    private void aNegativeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aNegativeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aNegativeButtonActionPerformed

    private void oPositiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oPositiveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oPositiveButtonActionPerformed

    private void aPositiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aPositiveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aPositiveButtonActionPerformed

    private void oNegativeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oNegativeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oNegativeButtonActionPerformed

    private void bNegativeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNegativeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bNegativeButtonActionPerformed

    private void abNegativeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abNegativeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abNegativeButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aNegativeButton;
    private javax.swing.JButton aPositiveButton;
    private javax.swing.JButton abNegativeButton;
    private javax.swing.JButton abPositiveButton;
    private javax.swing.JButton bNegativeButton;
    private javax.swing.JButton bPositiveButton;
    private javax.swing.JLabel bloodTypeLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel inventoryLabel;
    private javax.swing.JButton oNegativeButton;
    private javax.swing.JButton oPositiveButton;
    // End of variables declaration//GEN-END:variables
}
