
package BloodBankManagement;


import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
//import org.apache.poi.sl.usermodel.*;
//import org.apache.poi.ss.usermodel.*;
//import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import java.util.Random;

/**
 *
 * @author souleymane.sono
 */
public class NewDonor extends javax.swing.JInternalFrame {
    public String fname;
    private int rCount;
    

    /**
     * Creates new form CreateNewStudent
     */
    public NewDonor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        donationDetailsPanel = new javax.swing.JPanel();
        donorIDLabel = new javax.swing.JLabel();
        donationPlaceLabel = new javax.swing.JLabel();
        donorIDTextField = new javax.swing.JTextField();
        donationDateLabel = new javax.swing.JLabel();
        donationPlaceTextField = new javax.swing.JTextField();
        donationDateDateChooser = new com.toedter.calendar.JDateChooser();
        personalDetailsPanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        sexLabel = new javax.swing.JLabel();
        placeOfBirthLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        photoTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        middleNameTextField = new javax.swing.JTextField();
        middleNameLabel = new javax.swing.JLabel();
        sexComboBox = new javax.swing.JComboBox<>();
        dateOfBirthLabel = new javax.swing.JLabel();
        placeOfBirthTextField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        stateLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        stateComboBox = new javax.swing.JComboBox<>();
        zipTextField = new javax.swing.JTextField();
        zipLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        telephoneLabel = new javax.swing.JLabel();
        telephoneTextField = new javax.swing.JTextField();
        bloodTypeLabel = new javax.swing.JLabel();
        bloodTypeComboBox = new javax.swing.JComboBox<>();
        dateOfBirthDateChooser = new com.toedter.calendar.JDateChooser();
        emergencyContactPanel = new javax.swing.JPanel();
        firstNameECLabel = new javax.swing.JLabel();
        firstNameECTextField = new javax.swing.JTextField();
        lastNameECTextField = new javax.swing.JTextField();
        lastNameECLabel = new javax.swing.JLabel();
        telephoneECTextField = new javax.swing.JTextField();
        telephoneECLabel = new javax.swing.JLabel();
        relationshipECLabel = new javax.swing.JLabel();
        relationshipECTextField = new javax.swing.JTextField();
        printDonorRecordsButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        emailECLabel = new javax.swing.JLabel();
        emailECTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);
        setPreferredSize(new java.awt.Dimension(813, 1050));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Donor Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 0, 18))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(817, 1200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        donationDetailsPanel.setBackground(new java.awt.Color(239, 245, 250));
        donationDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Donation Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 0, 14))); // NOI18N
        donationDetailsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        donorIDLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        donorIDLabel.setText("Donor ID");
        donationDetailsPanel.add(donorIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 104, 27));

        donationPlaceLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        donationPlaceLabel.setText("Donation Place");
        donationDetailsPanel.add(donationPlaceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 119, 27));

        donorIDTextField.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        donorIDTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        donorIDTextField.setText("00000000");
        donationDetailsPanel.add(donorIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 166, 30));

        donationDateLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        donationDateLabel.setText("Donation Date");
        donationDetailsPanel.add(donationDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 119, 27));

        donationPlaceTextField.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        donationPlaceTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        donationDetailsPanel.add(donationPlaceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 140, -1));
        donationDetailsPanel.add(donationDateDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jPanel1.add(donationDetailsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 31, 788, 60));

        personalDetailsPanel.setBackground(new java.awt.Color(239, 245, 250));
        personalDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 0, 15))); // NOI18N

        firstNameLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        firstNameLabel.setText("First Name:*");

        sexLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        sexLabel.setText("Sex:");

        placeOfBirthLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        placeOfBirthLabel.setText("Place of Birth:");

        firstNameTextField.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        firstNameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        photoTextField.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        photoTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        photoTextField.setText("Insert Photo");
        photoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoTextFieldActionPerformed(evt);
            }
        });

        lastNameTextField.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        lastNameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });

        lastNameLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        lastNameLabel.setText("Last Name:*");

        middleNameTextField.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        middleNameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        middleNameLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        middleNameLabel.setText("Middle Name:*");

        sexComboBox.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        sexComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ", "Male", "Female" }));
        sexComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexComboBoxActionPerformed(evt);
            }
        });

        dateOfBirthLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        dateOfBirthLabel.setText("Date of Birth:");

        placeOfBirthTextField.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        placeOfBirthTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        addressLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        addressLabel.setText("Address:");

        addressTextField.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        addressTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        stateLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        stateLabel.setText("State:");

        cityLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        cityLabel.setText("City:");

        cityTextField.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        cityTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        stateComboBox.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        stateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        zipTextField.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        zipTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        zipLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        zipLabel.setText("Zip:");

        emailLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        emailLabel.setText("Email:");

        emailTextField.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        emailTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        telephoneLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        telephoneLabel.setText("Telephone:");

        telephoneTextField.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        telephoneTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        bloodTypeLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        bloodTypeLabel.setText("Blood Type");

        bloodTypeComboBox.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        bloodTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "A+", "A-", "B+", "B-", "AB+", "AB-", "O-", "O+" }));

        javax.swing.GroupLayout personalDetailsPanelLayout = new javax.swing.GroupLayout(personalDetailsPanel);
        personalDetailsPanel.setLayout(personalDetailsPanelLayout);
        personalDetailsPanelLayout.setHorizontalGroup(
            personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalDetailsPanelLayout.createSequentialGroup()
                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalDetailsPanelLayout.createSequentialGroup()
                        .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressTextField)
                            .addComponent(cityTextField)
                            .addComponent(emailTextField))
                        .addGap(26, 26, 26)
                        .addComponent(stateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(personalDetailsPanelLayout.createSequentialGroup()
                        .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(personalDetailsPanelLayout.createSequentialGroup()
                                    .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(firstNameTextField))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, personalDetailsPanelLayout.createSequentialGroup()
                                    .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, personalDetailsPanelLayout.createSequentialGroup()
                                    .addComponent(middleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(middleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(38, 38, 38)
                                    .addComponent(dateOfBirthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dateOfBirthDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, personalDetailsPanelLayout.createSequentialGroup()
                                    .addComponent(sexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sexComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(placeOfBirthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(placeOfBirthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(38, 38, 38)
                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalDetailsPanelLayout.createSequentialGroup()
                        .addComponent(photoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalDetailsPanelLayout.createSequentialGroup()
                        .addComponent(zipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(zipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))))
            .addGroup(personalDetailsPanelLayout.createSequentialGroup()
                .addComponent(telephoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telephoneTextField)
                .addGap(413, 413, 413))
            .addGroup(personalDetailsPanelLayout.createSequentialGroup()
                .addComponent(bloodTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bloodTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        personalDetailsPanelLayout.setVerticalGroup(
            personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalDetailsPanelLayout.createSequentialGroup()
                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(photoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(personalDetailsPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(middleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(middleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dateOfBirthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dateOfBirthDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(placeOfBirthTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sexComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(placeOfBirthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telephoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bloodTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.add(personalDetailsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 197, -1, 500));

        emergencyContactPanel.setBackground(new java.awt.Color(239, 245, 250));
        emergencyContactPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Emmergency Contact", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 0, 15))); // NOI18N

        firstNameECLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        firstNameECLabel.setText("First Name:*");

        firstNameECTextField.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        firstNameECTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lastNameECTextField.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        lastNameECTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lastNameECLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        lastNameECLabel.setText("Last Name:*");

        telephoneECTextField.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        telephoneECTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        telephoneECLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        telephoneECLabel.setText("Telephone:");

        relationshipECLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        relationshipECLabel.setText("Relationship:");

        relationshipECTextField.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        relationshipECTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        printDonorRecordsButton.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        printDonorRecordsButton.setText("Print Donor Records");
        printDonorRecordsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printDonorRecordsButtonMouseClicked(evt);
            }
        });
        printDonorRecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printDonorRecordsButtonActionPerformed(evt);
            }
        });

        clearButton.setBackground(new java.awt.Color(255, 0, 0));
        clearButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        clearButton.setForeground(new java.awt.Color(255, 255, 255));
        clearButton.setText("Clear");

        emailECLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        emailECLabel.setText("Email:");

        emailECTextField.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        emailECTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        addButton.setBackground(new java.awt.Color(51, 204, 0));
        addButton.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Add");
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout emergencyContactPanelLayout = new javax.swing.GroupLayout(emergencyContactPanel);
        emergencyContactPanel.setLayout(emergencyContactPanelLayout);
        emergencyContactPanelLayout.setHorizontalGroup(
            emergencyContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emergencyContactPanelLayout.createSequentialGroup()
                .addGroup(emergencyContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, emergencyContactPanelLayout.createSequentialGroup()
                        .addComponent(firstNameECLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstNameECTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, emergencyContactPanelLayout.createSequentialGroup()
                        .addComponent(telephoneECLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telephoneECTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, emergencyContactPanelLayout.createSequentialGroup()
                        .addGroup(emergencyContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailECLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(relationshipECLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(emergencyContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(relationshipECTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailECTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, Short.MAX_VALUE)
                .addComponent(lastNameECLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastNameECTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(emergencyContactPanelLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(addButton)
                .addGap(31, 31, 31)
                .addComponent(printDonorRecordsButton)
                .addGap(32, 32, 32)
                .addComponent(clearButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        emergencyContactPanelLayout.setVerticalGroup(
            emergencyContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emergencyContactPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(emergencyContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameECTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameECLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameECTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameECLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(emergencyContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telephoneECTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telephoneECLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(emergencyContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailECTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailECLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(emergencyContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(relationshipECLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(relationshipECTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(emergencyContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(printDonorRecordsButton)
                    .addComponent(clearButton))
                .addGap(14, 14, 14))
        );

        jPanel1.add(emergencyContactPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 710, 780, 280));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 800, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void photoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_photoTextFieldActionPerformed
    public String ReadExcel(String SheetName, int col){
        String Data = "";
        try{
            //FileInputStream fis = new FileInputStream("C:\\Users\\Souleymane.Sono\\OneDrive - Playtech\\Desktop\\data.xlsx");
            //Workbook wb = WorkbookFactory.create(fis);
            //org.apache.poi.ss.usermodel.Sheet s = wb.getSheet(SheetName);
            //Row r = s.getRow(row);
            //Cell c = r.getCell(col);
            //Data = c.getStringCellValue();
        }
        catch(Exception e){
            JOptionPane.showConfirmDialog(this, e);
            e.printStackTrace();   
        }
        return Data;
    }
    
    
    public void writeToExcel( 
            //String StudentID, 
            String firstname,
            String lastNamee,
            String dateObirth,
            String placeBirth, 
            String MiName,
            String gender,
            String Address,
            String State,
            String city,
            String Zip,
            String Tel,
            String AdmiNo,
            String admiDate,
            String email,
            String GuardFname,
            String GuardLname,
            String GuardTel,
            String GuardEmail,
            String Rship
            
    
    ){
        
    }
 
    private void printDonorRecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printDonorRecordsButtonActionPerformed
        // TODO add your handling code here:
        try{
            NewDonor obj = new NewDonor();
            String firstname = firstNameTextField.getText();
            String lastNamee = lastNameTextField.getText();
            //String dateObirth = DoB.getDateFormatString().toString();
            String placeBirth = placeOfBirthTextField.getText();
            String MiName = middleNameTextField.getText();
            String gender = (String) sexComboBox.getSelectedItem();
            String Address = addressTextField.getText();
            String State = (String)stateComboBox.getSelectedItem();
            String city = cityTextField.getText();
            String Zip = zipTextField.getText();
            String Tel = telephoneTextField.getText();
            String AdmiNo = donorIDTextField.getText();
            //String admiDate = adminDatee.getDate().toString();
            String email = emailTextField.getText();
            String GuardFname = firstNameECTextField.getText();
            String GuardLname = lastNameECTextField.getText();
            String GuardTel = telephoneECTextField.getText();
            String GuardEmail = emailECTextField.getText();
            String Rship = relationshipECTextField.getText();



           

        }catch(Exception e){
            JOptionPane.showConfirmDialog(this, e);
        
        
        }    
          
    }//GEN-LAST:event_printDonorRecordsButtonActionPerformed

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void printDonorRecordsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printDonorRecordsButtonMouseClicked
        
    }//GEN-LAST:event_printDonorRecordsButtonMouseClicked

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonMouseClicked

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    private void sexComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JComboBox<String> bloodTypeComboBox;
    private javax.swing.JLabel bloodTypeLabel;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JButton clearButton;
    private com.toedter.calendar.JDateChooser dateOfBirthDateChooser;
    private javax.swing.JLabel dateOfBirthLabel;
    private com.toedter.calendar.JDateChooser donationDateDateChooser;
    private javax.swing.JLabel donationDateLabel;
    private javax.swing.JPanel donationDetailsPanel;
    private javax.swing.JLabel donationPlaceLabel;
    private javax.swing.JTextField donationPlaceTextField;
    private javax.swing.JLabel donorIDLabel;
    private javax.swing.JTextField donorIDTextField;
    private javax.swing.JLabel emailECLabel;
    private javax.swing.JTextField emailECTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JPanel emergencyContactPanel;
    private javax.swing.JLabel firstNameECLabel;
    private javax.swing.JTextField firstNameECTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastNameECLabel;
    private javax.swing.JTextField lastNameECTextField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel middleNameLabel;
    private javax.swing.JTextField middleNameTextField;
    private javax.swing.JPanel personalDetailsPanel;
    private javax.swing.JTextField photoTextField;
    private javax.swing.JLabel placeOfBirthLabel;
    private javax.swing.JTextField placeOfBirthTextField;
    private javax.swing.JButton printDonorRecordsButton;
    private javax.swing.JLabel relationshipECLabel;
    private javax.swing.JTextField relationshipECTextField;
    private javax.swing.JComboBox<String> sexComboBox;
    private javax.swing.JLabel sexLabel;
    private javax.swing.JComboBox<String> stateComboBox;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JLabel telephoneECLabel;
    private javax.swing.JTextField telephoneECTextField;
    private javax.swing.JLabel telephoneLabel;
    private javax.swing.JTextField telephoneTextField;
    private javax.swing.JLabel zipLabel;
    private javax.swing.JTextField zipTextField;
    // End of variables declaration//GEN-END:variables
}
