/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package BloodBankManagement;

import BloodBankManagement.ActivityLog;
import BloodBankManagement.LoginPage;
import BloodBankManagement.NewUserForm;
import BloodBankManagement.User;

/**
 *
 * @author pault
 */
public class UpdateUserProfile extends javax.swing.JInternalFrame {
    
        //PAUL'S VARIABLES
    private String firstName;
    private String lastName;
    private String middleName;
    
    private String accountStatus;
    private String roleType;
    
    private String email;
    private String phoneNumber;
    
    private String username;
    private String password;
    
    private int userID;
    
    
    private String editUsername = null;
    private String currentUserPassword;

    /**
     * Creates new form UpdateUserProfile
     */
    public UpdateUserProfile() {
        initComponents();
        errorOptionPane.setVisible(false);
    }
    
    
    
        //PAUL'S METHODS
    
    //Show errorOptionPane and set text
    private void showError(String message, String title){
        errorOptionPane.setMessage(message);
        errorOptionPane.setVisible(true);
        
        try{
            errorOptionPane.createDialog(title).setVisible(true);
        } catch(Exception e){
            //handle exception, HeadlessException
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userDetailsPanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        middleNameLabel = new javax.swing.JLabel();
        middleNameTextField = new javax.swing.JTextField();
        accountStatusLabel = new javax.swing.JLabel();
        accountStatusComboBox = new javax.swing.JComboBox<>();
        roleTypeLabel = new javax.swing.JLabel();
        roleTypeComboBox = new javax.swing.JComboBox<>();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        telephoneLabel = new javax.swing.JLabel();
        telephoneTextField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        errorOptionPane = new javax.swing.JOptionPane();
        userPanel = new javax.swing.JPanel();
        editButton = new javax.swing.JButton();
        editUsernameTextField = new javax.swing.JTextField();
        currentUserPasswordField = new javax.swing.JPasswordField();
        editUsernameLabel = new javax.swing.JLabel();
        currentUserPasswordLabel = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(540, 850));

        userDetailsPanel.setBackground(new java.awt.Color(239, 245, 250));
        userDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 0, 18), new java.awt.Color(204, 0, 0))); // NOI18N

        firstNameLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        firstNameLabel.setText("First Name:*");

        firstNameTextField.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        firstNameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lastNameLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        lastNameLabel.setText("Last Name:*");

        lastNameTextField.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        lastNameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        middleNameLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        middleNameLabel.setText("Middle Name:");

        middleNameTextField.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        middleNameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        accountStatusLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        accountStatusLabel.setText("Account Status:*");

        accountStatusComboBox.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        accountStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Locked", "Unlocked" }));
        accountStatusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountStatusComboBoxActionPerformed(evt);
            }
        });

        roleTypeLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        roleTypeLabel.setText("Role Type:*");

        roleTypeComboBox.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        roleTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Admin", "Employee", "Guest" }));

        emailLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        emailLabel.setText("Email:");

        emailTextField.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        emailTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        telephoneLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        telephoneLabel.setText("Telephone:");

        telephoneTextField.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        telephoneTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        usernameLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        usernameLabel.setText("Username:*");

        usernameTextField.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        usernameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        passwordLabel.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        passwordLabel.setText("Password:*");

        passwordTextField.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        passwordTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        clearButton.setBackground(new java.awt.Color(255, 0, 0));
        clearButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        clearButton.setForeground(new java.awt.Color(255, 255, 255));
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(255, 0, 0));
        exitButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        errorOptionPane.setForeground(new java.awt.Color(204, 0, 51));
        errorOptionPane.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N

        javax.swing.GroupLayout userDetailsPanelLayout = new javax.swing.GroupLayout(userDetailsPanel);
        userDetailsPanel.setLayout(userDetailsPanelLayout);
        userDetailsPanelLayout.setHorizontalGroup(
            userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userDetailsPanelLayout.createSequentialGroup()
                        .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userDetailsPanelLayout.createSequentialGroup()
                                .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(userDetailsPanelLayout.createSequentialGroup()
                                .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(userDetailsPanelLayout.createSequentialGroup()
                                .addComponent(middleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(middleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(userDetailsPanelLayout.createSequentialGroup()
                                .addComponent(accountStatusLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(accountStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(userDetailsPanelLayout.createSequentialGroup()
                                .addComponent(roleTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(roleTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(userDetailsPanelLayout.createSequentialGroup()
                        .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userDetailsPanelLayout.createSequentialGroup()
                                .addComponent(telephoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(userDetailsPanelLayout.createSequentialGroup()
                                .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)))
                        .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(emailTextField)
                            .addComponent(telephoneTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userDetailsPanelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usernameLabel))
                    .addComponent(errorOptionPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(userDetailsPanelLayout.createSequentialGroup()
                            .addComponent(updateButton)
                            .addGap(18, 18, 18)
                            .addComponent(clearButton))
                        .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordTextField)
                            .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(exitButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        userDetailsPanelLayout.setVerticalGroup(
            userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(middleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(middleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roleTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roleTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telephoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userDetailsPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateButton)
                            .addComponent(clearButton))
                        .addGap(18, 18, 18)
                        .addComponent(exitButton))
                    .addGroup(userDetailsPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(errorOptionPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        userPanel.setBackground(new java.awt.Color(239, 245, 250));
        userPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 0, 18))); // NOI18N

        editButton.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        editUsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUsernameTextFieldActionPerformed(evt);
            }
        });

        editUsernameLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        editUsernameLabel.setText("Edit Username:");

        currentUserPasswordLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        currentUserPasswordLabel.setText("Current User Password:");

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editButton)
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editUsernameLabel)
                            .addComponent(currentUserPasswordLabel))
                        .addGap(18, 18, 18)
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(currentUserPasswordField)
                            .addComponent(editUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editUsernameLabel))
                .addGap(25, 25, 25)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentUserPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentUserPasswordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(userPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editUsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editUsernameTextFieldActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        //Take input
        editUsername = editUsernameTextField.getText();
        currentUserPassword = new String(currentUserPasswordField.getPassword());
        
        //Set users
        User currentUser = LoginPage.userHashMap.get(LoginPage.currentUsername);
        User editUser = LoginPage.userHashMap.get(editUsername);
        
        //Ensure Validity
        if(!currentUser.getPassword().equals(currentUserPassword)){
            showError("Incorrect password.", "User Verification Error");
            editUsername = null;
            return;
        } else if(editUser == null){
            showError("User does not exist.", "Input Validity Error");
            editUsername = null;
            return;
        } else if(!currentUser.getRoleType().equals("Admin")){
            showError("You do not have admin permission.", "User Verification Error");
            editUsername = null;
            return;
        } else if(editUser.getAccountStatus().equals("Locked")){
            showError("This user is locked.", "Input Validity Error");
            editUsername = null;
            return;
        } else if(editUser.getActive()){
            showError("Cannot edit the active user.", "User Verification Error");
            editUsername = null;
            return;
        }
        
        //Write in user information        
        firstNameTextField.setText(editUser.getFirstName());
        lastNameTextField.setText(editUser.getLastName());
        middleNameTextField.setText(editUser.getMiddleName());
        
        accountStatusComboBox.setSelectedItem(editUser.getAccountStatus());
        roleTypeComboBox.setSelectedItem(editUser.getRoleType());
        
        emailTextField.setText(editUser.getEmail());
        telephoneTextField.setText(editUser.getPhoneNumber());
        
        usernameTextField.setText(editUsername);
        passwordTextField.setText(editUser.getPassword());
        
        //Clear fields
        editUsernameTextField.setText("");
        currentUserPasswordField.setText("");
        
    }//GEN-LAST:event_editButtonActionPerformed

    private void accountStatusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountStatusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountStatusComboBoxActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        //Clear text fields
        firstNameTextField.setText("");
        lastNameTextField.setText("");
        middleNameTextField.setText("");

        accountStatusComboBox.setSelectedIndex(0);
        roleTypeComboBox.setSelectedIndex(0);

        emailTextField.setText("");
        telephoneTextField.setText("");

        usernameTextField.setText("");
        passwordTextField.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showConfirmDialog(this, "Added", JOptionPane.OK_CANCEL_OPTION);   OLD

        //Take input
        firstName = firstNameTextField.getText();
        lastName = lastNameTextField.getText();
        middleName = middleNameTextField.getText();

        accountStatus = accountStatusComboBox.getSelectedItem().toString();
        roleType = roleTypeComboBox.getSelectedItem().toString();

        email = emailTextField.getText();
        phoneNumber = telephoneTextField.getText();

        username = usernameTextField.getText();
        password = passwordTextField.getText();

        //Ensure fulfilled requirements
        if(firstName.equals("")){
            showError("First name is required.", "Input Validity Error");
            return; //No first name
        } else if(lastName.equals("")){
            showError("Last name is required.", "Input Validity Error");
            return; //No last name
        } else if(accountStatus.equals("Select")){
            showError("Account status is required.", "Input Validity Error");
            return; //Invalid account status
        } else if(roleType.equals("Select")){
            showError("Role is required.", "Input Validity Error");
            return; //Invalid role type
        } else if(username.equals("")){
            showError("Username is required.", "Input Validity Error");
            return; //No username
        } else if(editUsername == null){
            showError("No user chosen.", "Input Validity Error");
            return;
        } else if(LoginPage.userHashMap.containsKey(username) && !(username.equals(editUsername))){
            showError("Username is already taken.", "Input Validity Error");
            return; //Username already exists, and isn't the edited username
        } else if(password.equals("")){
            showError("Password is required.", "Input Validity Error");
            return; //No password
        }
        
        //Get userID
        userID = LoginPage.userHashMap.get(username).getUserID();

        //Update the user
        LoginPage.userHashMap.put(username, new User(firstName, lastName, middleName, accountStatus, roleType,
            email, phoneNumber, username, password, userID));

        //Clear text fields
        firstNameTextField.setText("");
        lastNameTextField.setText("");
        middleNameTextField.setText("");

        accountStatusComboBox.setSelectedIndex(0);
        roleTypeComboBox.setSelectedIndex(0);

        emailTextField.setText("");
        telephoneTextField.setText("");

        usernameTextField.setText("");
        passwordTextField.setText("");

        //Write action to log
        ActivityLog.writeToActivityLogFile("Updated user: " + username);

    }//GEN-LAST:event_updateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> accountStatusComboBox;
    private javax.swing.JLabel accountStatusLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JPasswordField currentUserPasswordField;
    private javax.swing.JLabel currentUserPasswordLabel;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel editUsernameLabel;
    private javax.swing.JTextField editUsernameTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JOptionPane errorOptionPane;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel middleNameLabel;
    private javax.swing.JTextField middleNameTextField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JComboBox<String> roleTypeComboBox;
    private javax.swing.JLabel roleTypeLabel;
    private javax.swing.JLabel telephoneLabel;
    private javax.swing.JTextField telephoneTextField;
    private javax.swing.JButton updateButton;
    private javax.swing.JPanel userDetailsPanel;
    private javax.swing.JPanel userPanel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
